apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: public
data:
  KAFKA_BROKERS: "10.1.21.87:9092,10.1.21.121:9092,10.2.4.20:9092"
  KAFKA_TOPIC: "ingress-nginx-logs"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-http-server
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-http-server
  template:
    metadata:
      labels:
        app: kafka-http-server
    spec:
      containers:
        - name: kafka-http-server
          image: eu-frankfurt-1.ocir.io/cnmegk4mhxmt/httptokafka:1.0
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TOPIC
      imagePullSecrets:
      - name: aliyun-registry
      dnsPolicy: ClusterFirs
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-http-server
  namespace: public
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kafka-http-server
